### ISSUE TITLE
systemd secrets for loading in some keys

### ISSUE THREAD

**Issue by Firstyear** [kanidm/hsm-crypto#10]
@arianvp may have some pointers about how to achieve this.

**Comment by arianvp** [comment]
https://systemd.io/CREDENTIALS/  gives a comprehensive explanation. Including how to seal the secrets to TPM

**Comment by yaleman** [comment]
^ should this have closed it?

**Comment by Firstyear** [comment]
In this case yes - the library now supports the ability to set a primate auth value on the root key of the HSM. This will be loaded from some external system like systemd here. 

I think we now need to open similar issues on Himmelblau / Kanidm for the Unix daemons to support this.
